import numpy as np
import xarray as xr

from arctichoke.dataset import get_variable_name

def find_standard_error(
    polyfit_residuals: xr.DataArray,
    n_dof: (int, float),
    verbose: bool = False,
    **kwargs,
):
    """ Sum a dataset by year along the time axis.

        Groups the dataset by year and sums each year.
        This results in one time step for each year in the given dataset.

        Parameters
        ----------
        polyfit_residuals : `int`, `float`, `xarray.DataArray`
            The array of sum of square residuals from the `polyfit_residuals` variable in the output of `xarray.polyfit` run with `full=True`. 
        n_dof : `int`, `float`
            The number of degrees of freedom to use.
        verbose : `bool`, optional
            Whether to verbosely output information as the function executes.
            Default is `False`.
        **kwargs
            Keyword arguments to handle extras that might have been passed by the function above this one.

        Returns
        -------
        standard_errors : `numpy.float64`, `xarray.DataArray`
            The standard error.
            If the data type of the given `polyfit_residuals` was `int` or `float`, the return type will be `numpy.float64`.
            If the data type of the given `polyfit_residuals` was `xarray.DataArray`, the return type will be `xarray.DataArray`.
        
        Examples
        --------
        >>> from arctichoke.analysis import find_standard_error
        >>> find_standard_error(175, 12)
        np.float64(4.183300132670378)
    """
    # Verify input arguments
    if not isinstance(polyfit_residuals, (int, float, xr.DataArray)):
        raise TypeError(f"(find_standard_error) `polyfit_residuals` must be a `xarray.DataArray`. Got type: {type(polyfit_residuals)}")
    if not isinstance(n_dof, (int, float)):
        raise TypeError(f"(find_standard_error) `n_dof` must be an integer or `float`. Got type: {type(n_dof)}")
    if not isinstance(verbose, bool):
        raise TypeError(f"(find_standard_error) `verbose` must be a `bool`. Got type: {type(verbose)}")
    
    # Calculate the standard error
    standard_errors = np.sqrt( polyfit_residuals / (n_dof - 2) )

    return standard_errors

def add_standard_error(
    dataset: (str, [str], xr.Dataset, xr.DataArray),
    verbose: bool = False,
    **kwargs,
):
    """ Add the standard error of the trend in a variable to the given dataset.

        If the given dataset contains trends generated by the `trend_in_time()` function, use the residuals of that trend to calculate the standard error and add that as a new variabl to the dataset.

        Parameters
        ----------
        dataset : `str`, `xarray.Dataset`
            The trends dataset for which to calculate the standard error.
        verbose : `bool`, optional
            Whether to verbosely output information as the function executes.
            Default is `False`.
        **kwargs
            Keyword arguments to handle extras that might have been passed by the function above this one.

        Returns
        -------
        dataset : `xarray.Dataset`
            The dataset with the additon of the standard error variable.
        
        Examples
        --------
        >>> from arctichoke.dataset import make_example_dataset
        >>> from arctichoke.path import make_file_path
        >>> test_file_dir = 'tests/test_analysis/example_datasets'
        >>> make_file_path(test_file_dir)
        >>> test_file_names = [
        >>>     f"{test_file_dir}/example_dataset_0.nc",
        >>>     f"{test_file_dir}/example_dataset_1.nc",
        >>>     f"{test_file_dir}/example_dataset_2.nc",
        >>> ]
        >>> offsets = [0, 1, 3]
        >>> for i in range(len(test_file_names)):
        >>>     make_example_dataset(
        >>>         n=3,
        >>>         offset=offsets[i],
        >>>         test_var_name='test_var',
        >>>         time_axis='year',
        >>>         time_len=2,
        >>>         start_year=(2000+i),
        >>>         save_as=test_file_names[i],
        >>>     )
        >>> import xarray as xr
        >>> test_dataset = xr.open_mfdataset(test_file_names, data_vars='all')
        >>> test_dataset['test_var'].values
        array([[[ 0.,  1.,  2.],
                [ 3.,  4.,  5.],
                [ 6.,  7.,  8.]],
               [[ 0.,  1.,  2.],
                [ 3.,  4.,  5.],
                [ 6.,  7.,  8.]],
               [[ 1.,  2.,  3.],
                [ 4.,  5.,  6.],
                [ 7.,  8.,  9.]],
               [[ 1.,  2.,  3.],
                [ 4.,  5.,  6.],
                [ 7.,  8.,  9.]],
               [[ 3.,  4.,  5.],
                [ 6.,  7.,  8.],
                [ 9., 10., 11.]],
               [[ 3.,  4.,  5.],
                [ 6.,  7.,  8.],
                [ 9., 10., 11.]]])
        >>> from arctichoke.analysis import trend_in_time
        >>> test_trends = trend_in_time(
        >>>     test_dataset,
        >>>     var='test_var',
        >>>     time_dim='time',
        >>> )
        >>> test_trends['test_var_trends'].values
        array([[1.49369, 1.49369, 1.49369],
               [1.49369, 1.49369, 1.49369],
               [1.49369, 1.49369, 1.49369]])
        >>> from arctichoke.analysis import add_standard_error
        >>> add_standard_error(test_trends)['test_var_trends_stderr'].values
        array([[0.30011687, 0.30011687, 0.30011687],
               [0.30011687, 0.30011687, 0.30011687],
               [0.30011687, 0.30011687, 0.30011687]])
    """
    # Verify input arguments
    if isinstance(dataset, str):
        # Verify this is a valid path
        datafile = verify_path(datafile)
        if not datafile.endswith('.nc'):
            raise TypeError(f"(add_standard_error) `datafile` must be a `.nc` filepath. Got: {datafile}")
        dataset = xr.open_dataset(dataset)
    elif not isinstance(dataset, xr.Dataset):
        raise TypeError(f"(add_standard_error) `dataset` must be a string or `xr.Dataset`. Got type: {type(dataset)}")
    if not isinstance(verbose, bool):
        raise TypeError(f"(add_standard_error) `verbose` must be a `bool`. Got type: {type(verbose)}")
    
    # Get the name of the original variable
    if 'original_variable' in dataset.attrs.keys():
        var = dataset.attrs['original_variable']
    else:
        raise ValueError(f"(add_standard_error) `dataset` does not have the `original_variable` attribute. Was `dataset` generated from `trend_in_time()`?")
    # Verify `dataset` has the specified variable as well as its trends and residuals
    actual_vars = get_variable_name(dataset)
    var_trend = f'{var}_trends'
    var_resid = f'{var}_residuals'
    for this_var in [var_trend, var_resid]:
        if this_var not in actual_vars:
            raise ValueError(f"(add_standard_error) `dataset` must have the variable {this_var}. Available variables: {actual_vars}")
    # Get the length of the original time dimension
    if 'original_time_length' in dataset.attrs.keys():
        len_time = dataset.attrs['original_time_length']
    else:
        raise ValueError(f"(add_standard_error) `dataset` does not have the `original_time_length` attribute. Was `dataset` generated from `trend_in_time()`?")
    
    # Calculate the standard error
    standard_errors = find_standard_error(
        dataset[var_resid],
        n_dof = len_time,
        verbose = verbose,
    )
    # Create the variable name for the standard errors
    stderr_name = f'{var_trend}_stderr'
    # Add the standard errors to the dataset
    dataset[stderr_name] = standard_errors

    # Modify the attributes of the dataset to reflect the changes
    dataset[stderr_name].attrs['standard_name'] = stderr_name
    if 'long_name' in dataset[var_trend].attrs.keys():
        dataset[stderr_name].attrs['long_name'] = f'Standard error of {dataset[var_trend].attrs['long_name']}'
    else:
        dataset[stderr_name].attrs['long_name'] = f'Standard error of {var_trend}'
    if 'units' in dataset[var_trend].attrs.keys():
        dataset[stderr_name].attrs['units'] = dataset[var_trend].attrs['units']
    else:
        dataset[stderr_name].attrs['units'] = 'N/P'
    if 'comment' in dataset[var_trend].attrs.keys():
        dataset[stderr_name].attrs['comment'] = f'Standard error of {dataset[var_trend].attrs['comment']}'
    else:
        dataset[stderr_name].attrs['comment'] = f'Standard error of {original_var_name}'

    return dataset
